name: Android Release
on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:

jobs:
  
  build:
    name: Create Android Build
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_supabase
  
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      - name: Upgrade dependencies
        run: flutter pub upgrade
      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk --no-tree-shake-icons --debug
        
      - name: Start release build for different cpu architectures
        run: flutter build apk --split-per-abi --no-tree-shake-icons --debug

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "flutter_supabase/build/app/outputs/flutter-apk/*.apk"
          tag: v1.0.${{ github.run_number }}
